forum/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='home'),
    path('<slug:slug>', views.MovieDetails.as_view(), name='movie_detail'),
    path(
        'genre/<slug:slug>', views.GenreDetail.as_view(), name='genre_detail'
        ),
]

watchit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('forum.urls'), name='forum_urls'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.db.models import Avg


class Movie(models.Model):
    """
    Movie Class model
    """
    movie_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, null=False, unique=True)
    movie_genre = models.ForeignKey(
        'Genre', on_delete=models.PROTECT, related_name='movie_genre'
        )
    director = models.CharField(max_length=200)
    year_released = models.DateField()
    synopsis = models.TextField()
    movie_poster = CloudinaryField('image', default='placeholder')
    movie_approved = models.BooleanField(default=False)
    movie_created_on = models.DateTimeField(auto_now_add=True)
    movie_updated_on = models.DateTimeField(auto_now=True)
    in_watchlists = models.ManyToManyField(
        User,
        related_name='in_watchlists',
        blank=True
    )

    class Meta:
        """
        Order our movies based on decreasing average rating order
        """
        # TO BE MODIFIED BY "-average_rating"
        ordering = ['-movie_created_on']

# Return String representation in Django doc:
    def __str__(self):
        return self.movie_title


RATING = (
    (0, "Not to prioritise"),
    (1, "Entertaining"),
    (2, "Must watch")
    )


class Review(models.Model):
    """
    Review Class model
    """
    reviewed_movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="movie_reviews"
        )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True,
        related_name="review_author"
        )
    content = models.TextField()
    movie_approved = models.BooleanField(default=False)
    review_rating = models.IntegerField(choices=RATING, default=1)
    review_created_on = models.DateTimeField(auto_now_add=True)
    review_updated_on = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        User, related_name="review_likes", blank=True
        )

    class Meta:
        ordering = ['-review_created_on', '-review_updated_on']

    def __str__(self):
        return f"Review by {self.author}: {self.content} - rating:{self.review_rating}"


STATUS = (
    (0, "Not yet watched"),
    (1, "Watched")
)


class WatchlistItem(models.Model):
    """
    WatchlistItem Class model
    """
    watchlistItem_movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="movie_watchlist"
        )
    watchlistItem_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_watchlist"
        )
    movie_status = models.IntegerField(choices=STATUS, default=0)
    added_on = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['-added_on']

    def __str__(self):
        return f"Added {self.watchlistItem_movie} to list of {self.watchlistItem_user}"


class Genre(models.Model):
    """
    Genre Class Model
    """
    genre_name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, null=False, unique=True)
    genre_image = CloudinaryField('image', default='placeholder')

    def __str__(self):
        return self.genre_name

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Movie, Review, WatchlistItem, Genre


def index(request):
    """
    View to return index.html as home page
    """
    return render(request, 'index.html')


class MovieList(generic.ListView):
    """
    Looks for Movie model and returns list:
    approved = True ordered by created date on home page
    """
    model = Movie
    queryset = Movie.objects.filter().order_by(
        '-movie_created_on'
        )
    template_name = 'index.html'
    # limiting number of posts that can appear on Movie page:
    paginate_by = 8

    def get_context_data(self, **kwargs):
        """
        Takes the genre object from Genre model
        and returns a list
        """
        context_data = super().get_context_data(**kwargs)
        context_data['genre_list'] = Genre.objects.all()
        return context_data


class WatchlistList(generic.ListView):
    """
    Looks for WatchlistItem model and returns list:
    movies approved = True ordered by added date on watchlist page
    """
    model = WatchlistItem
    queryset = WatchlistItem.objects.filter(
        ).order_by('-added_on')
    template_name = 'forum/watchlist.html'
    paginate_by = 12
    context_object_name = 'watchlist'


class MovieDetails(generic.ListView):
    """
    Displays movie object from Movie model &
    reviews posted on this object.
    """

    def get(self, request, slug, *args, **kwargs):
        """
        Gets full movie detail with approved reviews
        """
        queryset = Movie.objects.filter(movie_approved=True)
        movie = get_object_or_404(queryset, slug=slug)
        reviews = movie.reviews.order_by('-review_created_on')

        return render(
            request,
            'forum/movie_detail.html',
            {
                'movie': movie,
                'reviews': reviews,
                'reviewed': False,
            },
        )


class GenreDetail(generic.View):
    """
    Returns all the movie objects from the Movie model
    filtered by a genre and with movie_approved = True
    """

    def get(self, request, slug, *args, **kwargs):
        """
        Get all the genre objects from the Genre model
        and the specific slug of the genre object
        Gets all the movie objects filtered then by
        their genre with movie_approved = True
        returns the single genre object instance,
        the movie object and the genre object list
        """

        genre_object = Genre.objects.all()
        genres = get_object_or_404(genre_object, slug=slug)
        movies = genres.movie_genre.filter(
            movie_approved=True).order_by('-movie_created_on')

        return render(
            request,
            'forum/genre.html',
            {
                'movies': movies,
                'genres': genres,
                'genre_object': genre_object
            },
        )

forum/templates/genre.html
{% extends "base.html" %} {% load static %}{% block title %}
<title>{{ genres }} Genre</title>
{% endblock %} {% block content %}{% load ratings %}

<section class="pb-5 pt-5">
  <div class="row justify-content-center">
    <div class="col col-sm-10">
      <h1 class="page-title mt-5 mb-5">{{ genres }}</h1>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col">
      <div class="container-fluid">
        <div class="row">
          <!-- Movie Listing for specific Genres -->
          <div class="col-12">
            <div class="row">
              {% for movie in movies %} {% if movie.movie_genre == genres %}
              <div class="col-12 col-md-4 col-lg-3 mb-3 mb-md-5">
                <a href="{% url 'movie_detail' movie.slug %}">
                  <div class="card h-100 book-card">
                    <div class="card-header">
                      <h2 class="mt-2 f-small p-bold">
                        {{ movie.title }}
                        <span class="irresistable f-small p-bold"
                          >by {{ movie.director }}</span
                        >
                      </h2>
                      <!--https://django-star-ratings.readthedocs.io/en/latest/?badge=latest/#-->
                      <div class="star">
                        {% ratings movie 12 12 read_only %}
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-4 d-flex align-items-center p-0">
                        <div class="card-body p-0">
                          {% if "placeholder" in movie.movie_poster.url %}
                          <img
                            class="card-img-top image-listing"
                            src="https://res.cloudinary.com/ddhmc5wvm/image/upload/v1661075789/book-nook/images/bookworm-3.png"
                            alt="{{ movie.title }} by {{ movie.director }} movie listing with no poster"
                          />
                          {% else %}
                          <img
                            class="card-img-top image-listing"
                            src=" {{ movie.movie_poster.url }}"
                            alt="{{ movie.title }} by {{ movie.director }} movie listing"
                          />
                          {% endif %}
                        </div>
                      </div>
                      <div class="col-7 d-flex align-items-center">
                        <p class="f-small card-text">
                          {{movie.synopsis|truncatewords:40}}
                        </p>
                      </div>
                    </div>
                  </div>
                </a>
              </div>

              {% if forloop.counter|divisibleby:8 %}
            </div>
            <div class="row">
              {% endif %} {% endif %} {% empty %}
              <h2 class="text-center">No movies in this genre added yet</h2>
              {% endfor %}
            </div>
          </div>
        </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
              <a
                href="?page={{ page_obj.previous_page_number }}"
                class="page-link"
                >&laquo; PREV
              </a>
            </li>
            {% endif %} {% if page_obj.has_next %}
            <li>
              <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                NEXT &raquo;</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
      </div>
    </div>
  </div>
</section>

<!--More Genres section-->
<section id="more-genres" class="pb-5 pt-5">
  <h3 class="text-center">More Genres</h3>
  <!--Owl Carousel https://owlcarousel2.github.io/OwlCarousel2/-->
  <div class="owl-carousel owl-theme">
    {% for value in genre_object %}
    <div class="item">
      <div class="card h-100 genre-card">
        <div class="card-body p-0">
          <a href="{% url 'genre_detail' value.slug %}">
            <div
              class="p-0 card-header genre-card-title d-flex align-items-center justify-content-center"
            >
              <h4 class="m-0 f-medium p-bold card-title text-center">
                {{ value.genre_name }}
              </h4>
            </div>
            <img
              class="card-img genre-card-img"
              src=" {{ value.genre_image.url }} "
              alt="image associated with {{ genre.genre.name }}"
            />
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock %} {% block script %}
<!-- Script for owl carousel initilisation and settings-->
<script>
  $(".owl-carousel").owlCarousel({
    loop: true,
    margin: 10,
    nav: true,
    dots: false,
    responsive: {
      0: {
        items: 1,
      },
      300: {
        items: 3,
      },
      600: {
        items: 5,
      },
      1000: {
        items: 7,
      },
    },
  });
</script>
{% endblock %}

forum/templates/movie_detail.html
<!-- prettier-ignore -->
{% extends "base.html" %} {% load static %}
{% block title %} <title>{{ movie.movie_title }}!</title> {% endblock %}
<!-- prettier-ignore -->
{% block content %}

<section>
  <!-- Header part of the movie detail -->
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div
        class="col-auto mt-3 col-md-3 d-flex justify-content-md-end justify-content-lg-center"
      >
        <img
          class="card-img-top book-detail-image"
          src=" {{ movie.movie_poster.url }}"
          alt="{{ movie.movie_title }} by {{ movie.director }} movie details"
        />
      </div>
      <div class="col-auto p-0 mt-3 col-md-6">
        <div class="row align-items-center">
          <div class="col-12 p-0">
            <h1 class="text-center text-md-start">{{ movie.movie_title }}</h1>
          </div>
          <div class="p-0 col-12">
            <h2 class="p-bold text-center text-md-start">
              by {{ movie.director }}
            </h2>
          </div>
          <div class="row justify-content-center justify-content-md-start mt-3">
            <div
              class="p-0 col-12 mb-3 mb-md-5 d-flex justify-content-center justify-content-md-start col-md-5 col-lg-3"
            >
              <!--https://django-star-ratings.readthedocs.io/en/latest/?badge=latest/#-->
              {% ratings movie %}
            </div>
            <div class="p-0 col-4 col-lg-3 d-flex justify-content-center">
              <a href="#reviews" class="btn btn-styles review-btn">Review</a>
            </div>

            {% if user.is_authenticated %}
            <div class="p-0 col-3 mt-2">
              <div
                class="d-flex justify-content-center justify-content-md-start"
              >
                <form
                  class="d-inline"
                  action="{% url 'watchlist_movie' movie.slug %}"
                  method="POST"
                >
                  {% csrf_token %} {% if favourite %}
                  <span class="text-secondary"
                    >{{ movie.count_in_watchlists }}
                  </span>
                  <button
                    type="submit"
                    name="movie_id"
                    value="{{movie.slug}}"
                    class="btn-like"
                  >
                    <i class="fa-solid fa-bookmark"></i>
                  </button>
                  {% else %}
                  <span class="text-secondary">{{ movie.in_watchlists }} </span>
                  <button
                    type="submit"
                    name="movie_id"
                    value="{{movie.slug}}"
                    class="btn-like"
                  >
                    <i class="fa-regular fa-bookmark"></i>
                  </button>
                  {% endif %}
                </form>
              </div>
            </div>
            {% else %}
            <div class="p-0 col-md-3 col-12 mt-4 mt-md-2">
              <div class="row">
                <div class="col p-0 d-flex justify-content-center">
                  <span class="text-center p-bold"
                    >{{ movie.in_watchlists }}
                    <i class="fa-regular fa-bookmark"></i
                  ></span>
                </div>
              </div>
              <div class="row">
                <div class="col p-0 d-flex justify-content-center p-0">
                  <span class="p-bold text-center f-small"
                    ><a class="f-small" href="{% url 'account_login' %}"
                      >Log In</a
                    >
                    or
                    <a class="f-small" href="{% url 'account_signup' %}"
                      >Sign Up</a
                    >
                    to add to Watchlist</span
                  >
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="row justify-content-center">
      <div class="col col-md-8">
        <h3 class="h3-styles">Blurb</h3>
        {{ movie.synopsis | linebreaks }}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WatchIt!</title>

    <!-- Import for Google Fonts Lato & Poppins -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&family=Poppins:wght@300;400;700&display=swap"
      rel="stylesheet"
    />
    <!-- Import stylesheet CDN Font-Awesome 6.2.1 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Import Bootstrap 5.2.2 CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />

    <!-- Import Owl Carousel CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
      integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css"
      integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!-- Import Django Star Ratings -->
    <link
      rel="stylesheet"
      href="{% static 'star-ratings/css/star-ratings.css' %}"
    />
    <script
      type="text/javascript"
      src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"
    ></script>

    <!-- Link to CSS file -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <!-- Navigation bar -->

    <nav class="navbar sticky-top navbar-expand-lg navbar-dark red-bg">
      <a class="navbar-brand" href="{% url 'home' %}"
        ><span>Watch</span><span>It!</span></a
      >
      <!-- Search functionality in Navbar -->
      <div class="align-items-center justify-content-center mb-3">
        <div class="text-center">
          <form class="d-inline-flex col-10" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
          </form>
        </div>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="flex">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"
                  ><i class="fa-solid menu-icon fa-film"></i>Movies</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"
                  ><i class="fa-solid fa-fire"></i>Trending</a
                >
              </li>
              <!-- Navbar links to display based on user type (auth or not) -->
              {% if user.is_authentificated %}
              <li class="nav-item">
                <a class="nav-link" href="#"
                  ><i class="fa-duotone fa-bookmark"></i>My Watchlist</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"
                  ><i class="fa-solid fa-right-from-bracket"></i>Logout</a
                >
              </li>
              {% else %}
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                  ><i class="fa-solid fa-user"></i>Login/Register
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Login</a></li>
                  <li><a class="dropdown-item" href="#">Register</a></li>
                </ul>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <!-- Page content comes here -->
    {% block content %}{% endblock content %}

    <!-- Footer -->
    <footer class="red-bg text-center mt-auto">
      <div class="container-fluid p-6">
        <div class="col align-self-center">
          <div class="footer-icon-container">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="https://github.com/nfepb" target="_blank">
                  <i
                    class="fa-brands fa-3x fa-square-github white-icon"
                    aria-hidden="true"
                  ></i>
                  <span class="sr-only">Github</span>
                </a>
              </li>
              <li class="list-inline-item">
                <a
                  href="https://www.linkedin.com/in/nicolas-plante-bordeneuve/"
                  target="_blank"
                >
                  <i
                    class="fa-brands fa-3x fa-linkedin white-icon"
                    aria-hidden="true"
                  ></i>
                  <span class="sr-only">LinkedIn</span>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-text">
            &copy; Copyright 2022. Nicolas Planté-Bordeneuve.
          </div>
          <div class="copyright-text">
            This project is made for educational purposes only. No commercial
            revenue is generated from the project.
          </div>
        </div>
      </div>
    </footer>

    <!-- Import Bootstrap JavaScript -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>

    <!-- Import jQuery JavaScript -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
      integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <!-- Import Owl Carousel JavaScript -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
      integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <!-- Additional page scripts are added here -->
    {% block script %}{% endblock %}
  </body>
</html>

templates/index.html
<!-- prettier-ignore -->
{% extends "base.html" %} {% load static %}
{% block title %} <title>WatchIt!</title> {% endblock %}
<!-- prettier-ignore -->
{% block content %}

<section id="hero-section">
  <div class="container-fluid">
    <div class="row">
      <div
        class="flex-column col-12 col-md-7 col-lg-6 align-items-center text-center"
      >
        <img
          class="hero-image"
          src="https://res.cloudinary.com/dknv0nxqz/image/upload/v1668944494/watchit/static/images/hero-image-watchit_euj5ql.png"
          alt="Image of 3D Glasses on pop corn"
        />
      </div>
      <div
        class="row flex-column col-12 col-md-7 col-lg-6 align-items-center justify-content-center text-center"
      >
        <h1 class="main-title pt-5 pb-3">WatchIt!</h1>
        <h2 class="secundary-title">
          Review your favorite movies and find your next one to watch!
        </h2>
        <h3 class="third-title">Discover new horizons in the 7th Art</h3>
        {% if user.is_authentificated %}
        <h3>Welcome {{ user }}</h3>
        <a class="btn btn-hero btn-secondary" href="#">My watchlist</a>
        {% else %}
        <div class="d-flex justify-content-around pt-3 pb-3">
          <a class="btn btn-hero btn-danger" href="#">Login</a>
          <a class="btn btn-hero btn-outline-danger" href="#">Sign Up</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

<!-- Movie carousel section  -->
<section id="carousel-section">
  <h2 class="text-center">Newly added movies</h2>
  <!-- Owl Carousel https://owlcarousel2.github.io/OwlCarousel2/ -->
  <div class="owl-carousel owl-theme">
    {% for movie in movie_list %}
    <div class="item">
      <div class="card h-100 card-home border-0">
        <div class="card-body movie-listing-body">
          <a href="{% url 'movie_detail' movie.slug %}">
            <img
              class="card-img-top owl-movie-listing"
              src=" {{ movie.movie_poster.url }}"
              alt="{{ movie.title }} by {{ movie.year_released }} movie listing"
            />
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
<!-- Genre Section -->
<section id="genres-section">
  <h3 class="text-center page-subtitle">Discover by genre</h3>
  <!--Owl Carousel https://owlcarousel2.github.io/OwlCarousel2/-->
  <div class="owl-carousel owl-theme">
    {% for genre in genre_list %}
    <div class="item">
      <div class="card h-100 genre-card">
        <div class="card-body p-0">
          <a href="{% url 'genre_name' genre.slug %}">
            <div
              class="p-0 card-header genre-card-title d-flex align-items-center justify-content-center"
            >
              <h4 class="m-0 f-medium p-bold card-title text-center">
                {{ genre.genre_name }}
              </h4>
            </div>
            <img
              class="card-img genre-card-img"
              src=" {{ genre.genre_image.url }} "
              alt="image associated with {{ genre.genre.name }}"
            />
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %} {% block script %}
<!-- Owl Carousel script with settings from https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html-->
<script>
  $(".owl-carousel").owlCarousel({
    loop: true,
    margin: 10,
    nav: true,
    responsive: {
      0: {
        items: 1,
      },
      600: {
        items: 4,
      },
      1000: {
        items: 8,
      },
    },
  });
</script>
{% endblock %}